### ISSUE TITLE
Product Vision

### ISSUE THREAD

**Issue by mr1er0y** [mr1er0y/Console-Organizer#1]
@nvamelichev, посмотрите и оцените, пожалуйста, наш  Product Vision

**Comment by nvamelichev** [comment]
- [x] Нет краткого описания ("в двух словах, о чём проект?"), сразу идёт детальное описание функциональности :-(
- [x] > хранит дела или мероприятия в формате TODO списка.
      > Пользователь может добавлять дела, ставить дедлайны к ним. 
      > Помимо основной работы с приложением у пользователя будет опция переноса данного TODO списка в календарь или в заметки. 
      > Также мы хотим добавить возможность привязывать событие к конкретному человеку из списка контактов.
Вот это всё &mdash; аж четыре User Story, которые маскируются под кусочек Product Vision. Проработайте их, и будет прекрасный список User Stories :-)
- [x] "опция переноса данного TODO списка в календарь или в заметки" - поясните, что имеется в виду. Экспорт записей в стандартные форматы календаря типа vCalendar, vCard, ...? Экспорт в форматы конкретных приложений календаря и заметок для определённых ОС?
- [x] "возможность привязывать событие к конкретному человеку из списка контактов" - у вас будет управление контактами? Интересно. Раскройте эту тему в User Stories
- [x] "Проект облегчит жизнь растерянным и несобранным людям." - Тут "растерянные и несобранные" люди будут расстроены, а ведь они - ваша целевая аудитория. Рекомендую переформулировать, например, "Проект поможет пользователю упорядочить свои дела, успевать больше, освободить больше времени для действительно важных вещей"
- [x] Ещё совершенно не затронута тема синхронизации, а она, как мне кажется, тут важная, и добавляет плюсов проекту. Идея TODO.txt в том, чтобы положить элементарный текстовый файлик в своё облачное хранилище (Google Drive, Dropbox, Яндекс.Диск, Mail.Ru Облако, ...) и иметь его всегда с собой на всех устройствах. И формат настолько простой, что на всех устройствах поддержан, а где нет - всегда есть "Блокнот". Соответственно, используя формат TODO.txt, ваш проект позволяет юзеру управлять делами везде, где есть консоль :-D.

**И очень жду от вас первую версию User Stories!!!**

**Comment by nvamelichev** [comment]
Обновлённый Product Vision принимается, молодцы! :+1: 

Issue можно закрывать :-)
